# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:20-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package.json package.json

# Install dependencies
RUN --mount=type=cache,target=/root/.npm npm install --ignore-scripts

# Copy the rest of the application code
COPY src/ src/
COPY tsconfig.json tsconfig.json

# Build the TypeScript code
RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

# Copy the build output and package.json to the runner stage
COPY --from=builder /app/build build
COPY --from=builder /app/package.json package.json
COPY --from=builder /app/package-lock.json package-lock.json

# Install production dependencies
RUN npm ci --ignore-scripts --omit=dev

# Expose port 3000 (if the server listens on this port)
EXPOSE 3000

# Command to run the MCP server
ENTRYPOINT ["node", "build/index.js"]
